apiVersion: llmd.ai/v1alpha1
kind: VariantAutoscaling
metadata:
  name: dev-model-va
  namespace: llm-d-sim
  labels:
    inference.optimization/acceleratorName: A100
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: dev-model-decode
  modelID: test-model
  minReplicas: 1
  maxReplicas: 4
  variantCost: "30.0"
